[font]
size = 9.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/fish"

[cursor]
blink_interval = 750
unfocused_hollow = true
# thickness = 0.15

[cursor.style]
shape = "Beam"
blinking = "Always"
